# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'banks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\x12\'project1_distributed_systems_jesse_zigi\"\x84\x01\n\x0f\x43ustomerMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x45\n\tinterface\x18\x02 \x01(\x0e\x32\x32.project1_distributed_systems_jesse_zigi.Interface\x12\x13\n\x06\x61mount\x18\x03 \x01(\x03H\x00\x88\x01\x01\x42\t\n\x07_amount\"f\n\rBranchMessage\x12\x45\n\tinterface\x18\x01 \x01(\x0e\x32\x32.project1_distributed_systems_jesse_zigi.Interface\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"\xb1\x01\n\x05Reply\x12\x45\n\tinterface\x18\x01 \x01(\x0e\x32\x32.project1_distributed_systems_jesse_zigi.Interface\x12?\n\x06result\x18\x02 \x01(\x0e\x32/.project1_distributed_systems_jesse_zigi.Result\x12\x14\n\x07\x62\x61lance\x18\x03 \x01(\x03H\x00\x88\x01\x01\x42\n\n\x08_balance*1\n\tInterface\x12\x0c\n\x08WITHDRAW\x10\x00\x12\x0b\n\x07\x44\x45POSIT\x10\x01\x12\t\n\x05QUERY\x10\x02*\"\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xf7\x01\n\rBranchService\x12q\n\x05Query\x12\x38.project1_distributed_systems_jesse_zigi.CustomerMessage\x1a..project1_distributed_systems_jesse_zigi.Reply\x12s\n\tPropagate\x12\x36.project1_distributed_systems_jesse_zigi.BranchMessage\x1a..project1_distributed_systems_jesse_zigi.Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERFACE']._serialized_start=475
  _globals['_INTERFACE']._serialized_end=524
  _globals['_RESULT']._serialized_start=526
  _globals['_RESULT']._serialized_end=560
  _globals['_CUSTOMERMESSAGE']._serialized_start=57
  _globals['_CUSTOMERMESSAGE']._serialized_end=189
  _globals['_BRANCHMESSAGE']._serialized_start=191
  _globals['_BRANCHMESSAGE']._serialized_end=293
  _globals['_REPLY']._serialized_start=296
  _globals['_REPLY']._serialized_end=473
  _globals['_BRANCHSERVICE']._serialized_start=563
  _globals['_BRANCHSERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
