# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banks_pb2 as banks__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in banks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BranchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/project3_distributed_systems_jesse_zigi.BranchService/Query',
                request_serializer=banks__pb2.CustomerMessage.SerializeToString,
                response_deserializer=banks__pb2.Reply.FromString,
                _registered_method=True)
        self.Propagate = channel.unary_unary(
                '/project3_distributed_systems_jesse_zigi.BranchService/Propagate',
                request_serializer=banks__pb2.BranchMessage.SerializeToString,
                response_deserializer=banks__pb2.Reply.FromString,
                _registered_method=True)


class BranchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """RPC for customer to branch requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propagate(self, request, context):
        """RPC for branch to branch requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=banks__pb2.CustomerMessage.FromString,
                    response_serializer=banks__pb2.Reply.SerializeToString,
            ),
            'Propagate': grpc.unary_unary_rpc_method_handler(
                    servicer.Propagate,
                    request_deserializer=banks__pb2.BranchMessage.FromString,
                    response_serializer=banks__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3_distributed_systems_jesse_zigi.BranchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3_distributed_systems_jesse_zigi.BranchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BranchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3_distributed_systems_jesse_zigi.BranchService/Query',
            banks__pb2.CustomerMessage.SerializeToString,
            banks__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propagate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3_distributed_systems_jesse_zigi.BranchService/Propagate',
            banks__pb2.BranchMessage.SerializeToString,
            banks__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
